### ISSUE TITLE
messages only fetch a line of content (fix in 6646abd doesn't work in python3)

### ISSUE THREAD

**Issue by jcea** [IvanMalison/okcupyd#36]
```
print user.inbox[0].messages[0].content
```

only fetches the first line of the message.

**Comment by IvanMalison** [comment]
Thanks for reporting this. Can you give a sample message that doesn't work?

**Comment by jcea** [comment]
Any message I test with multiple paragraphs. When I fetch the message only the first line is retrieved.

**Comment by IvanMalison** [comment]
Yep. I pushed a fix to master. Can you test it. I think it might not handle trailing whitespace properly

**Comment by jcea** [comment]
Ivan, I have patched my copy of "okcupyd" and I don't see any effect :-(. Still getting only the first line. :-?

**Comment by IvanMalison** [comment]
Can setup.py install? How exactly did you patch?

**Comment by jcea** [comment]
My mistake. I patched the version installed under Python 3.4. This code doesn't work under Python 3, by the way, althought it is documented in the PYPI page.

Doing "pip2.7 install -U okcupyd" I install version 0.8.17, released today. Same problem. I fetch only the first line of the messages :-(. In my case the paragraphs are separated by empty lines. Something like this:

```
first paragraph
(empty line)
second paragraph
```
Maybe this help you.

**Comment by IvanMalison** [comment]
I haven't done an okcupyd release with the fix for this problem yet. I did a release earlier today for another problem. What do you mean it doesn't work in python3? It works in python3 for me... all of the tests run is python3 as well.

**Comment by jcea** [comment]
Forget the Python 3 issue for now. I was maybe having a dependency issue. Didn't investigate it.

Patching by hand.

Running in Python 3 I get this:

```
Traceback (most recent call last):
  File "./z.py", line 20, in <module>
    thread = [(j.time_sent, j.sender.username, j.recipient.username, j.content) for j in i.messages]
  File "./z.py", line 20, in <listcomp>
    thread = [(j.time_sent, j.sender.username, j.recipient.username, j.content) for j in i.messages]
  File "/usr/local/lib/python3.4/site-packages/okcupyd/util/__init__.py", line 49, in __get__
    value = self.func(obj)
  File "/usr/local/lib/python3.4/site-packages/okcupyd/messaging.py", line 140, in content
    for i in message.iterchildren()])
  File "/usr/local/lib/python3.4/site-packages/okcupyd/messaging.py", line 140, in <listcomp>
    for i in message.iterchildren()])
TypeError: expected bytes, bytearray or buffer compatible object
```

It seems to work under Python 2.7. GOOD!.

**Comment by IvanMalison** [comment]
Yeah, I'll do a pypi release later in the day so you don't have to patch by hand. Did you check what happens with adding trailing whitespace? I guess that doesn't really matter much... okcupyd does some really strange stuff in general, so it may be hard to preserve the message exactly as sent.

**Comment by jcea** [comment]
Good. Let me know when I can install the update (working in Python 3 too! :).

I can't do experiments now because the OKC mailbox is full at the moment. Dumping the messages to my laptop what the point of messing with this :). Sorry.

**Comment by IvanMalison** [comment]
haha, cool. Are you using the built in sqlalchemy functionality for dumping the messages? you should check that out if you aren't.

You are right about python 3. there is a unicode error with the current implementation. I will do a release later today that works for both pythons.

**Comment by jcea** [comment]
The code is:

```
#!/usr/bin/env python3

import time, sys, pickle

import okcupyd

okcupyd.settings.USERNAME = 'XXXX'
okcupyd.settings.PASSWORD = 'XXXX'

user = okcupyd.User()

t = int(time.time())

if len(sys.argv) == 1:
    for i in user.inbox :
        print(i.correspondent)
else :
    for i in user.inbox :
        if i.correspondent == sys.argv[1] :
            thread = [(j.time_sent, j.sender.username, j.recipient.username, j.content) for j in i.messages]
            print(thread)
            with open('%s.%d.pickle' %(sys.argv[1], t), 'wb') as f :
                pickle.dump(thread, f, protocol=pickle.HIGHEST_PROTOCOL)
            t += 1


```

**Comment by IvanMalison** [comment]
syncing using the built in sqlalchemy database would be really easy:

Check out https://github.com/IvanMalison/okcupyd/blob/master/okcupyd/tasks/db.py#L3

you can run that using invoke:

Something like:
inv okcupyd.credentials (credentials_file) okcupyd.db.sync

should do exactly what you want.

This will store everything in a sqlite database, which you can then access with orm models like:
https://github.com/IvanMalison/okcupyd/blob/master/okcupyd/db/model/message.py

The advantage over pickling is that everything is linked together, so you can navigate between users, messages, and message thread with ease. It will also synchronize with okcupid by only updating unknown messages.

**Comment by jcea** [comment]
What happens if I delete messages and threads in OKC?. Are they preserved in the local dump?

**Comment by IvanMalison** [comment]
I'd need to double check the code, but that is almost certainly what happens. I don't think that anything is ever deleted anywhere.

**Comment by IvanMalison** [comment]
@jcea The new version on pypi has a patch that works for python 2 and 3. Let me know if it works for you.

**Comment by jcea** [comment]
Looks good, both Python 2.7 and Python 3.4. Thanks.
